name: Build

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows running this action manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make
      working-directory: argon2
      run: make test
