name: Build

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows running this action manually
  workflow_dispatch:

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      working-directory: argon2
      run: make test

    - name: Results
      working-directory: argon2
      run: ls

  mac:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      working-directory: argon2
      run: make test

    - name: Results
      working-directory: argon2
      run: ls
